name:                int-like
version:             0.1.3
github:              "ejconlon/int-like"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2022 Eric Conlon"
category:            "Data Structures"
synopsis:            "Newtype wrappers over IntSet and IntMap"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/int-like#readme>

dependencies:
- base >= 4.12 && < 5
- algebraic-graphs >= 0.7 && < 0.8
- containers >= 0.6 && < 0.7
- deepseq >= 1.4 && < 1.5
- hashable >= 1.3 && < 1.5

default-extensions:
- BangPatterns
- ConstraintKinds
- DeriveAnyClass
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MultiParamTypeClasses
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds
- -fwrite-ide-info
- -hiedir=.hie

library:
  source-dirs: src

tests:
  int-like-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - int-like
    - tasty
    - tasty-hunit
