name:                int-like
version:             0.1.4
github:              "ejconlon/int-like"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2022 Eric Conlon"
category:            "Data Structures"
synopsis:            "Newtype wrappers over IntSet and IntMap"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/int-like#readme>

dependencies:
- base >= 4.12 && < 5
- algebraic-graphs >= 0.7 && < 0.9
- containers >= 0.6 && < 0.9
- deepseq >= 1.4 && < 1.6
- hashable >= 1.3 && < 1.6

default-extensions:
- BangPatterns
- ConstraintKinds
- DeriveAnyClass
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MultiParamTypeClasses
- QuantifiedConstraints
- Rank2Types
- RoleAnnotations
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds
- -fwrite-ide-info
- -hiedir=.hie

library:
  source-dirs: src

